# Generated by Django 5.0.1 on 2024-02-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_delete_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
