# Generated by Django 5.0.1 on 2024-02-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_Image',
            field=models.ImageField(blank=True, default='images/defaultvenderimg.png', null=True, upload_to='profile_img'),
        ),
    ]
