# Generated by Django 5.0.1 on 2024-02-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_Image',
        ),
    ]
