# Generated by Django 5.0.1 on 2024-02-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_Vender',
            field=models.BooleanField(default=False, verbose_name='Is Vender'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Is Customer '),
        ),
    ]
