# Generated by Django 5.0.1 on 2024-02-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_customuser_is_vender_customuser_is_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_customer',
        ),
    ]
