# Generated by Django 5.0.1 on 2024-02-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_customuser_is_vender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_Vender',
            field=models.BooleanField(default=False),
        ),
    ]
