# Generated by Django 5.0.1 on 2024-02-20 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='content',
        ),
    ]
