# Generated by Django 5.0.1 on 2024-02-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_rename_content_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
