# Generated by Django 5.0.1 on 2024-02-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_rename_email_contact_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_venuecoordinator',
            field=models.BooleanField(default=False),
        ),
    ]
