# Generated by Django 5.0.1 on 2024-02-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couples',
            options={'verbose_name': 'Couples', 'verbose_name_plural': 'Couples'},
        ),
        migrations.AlterField(
            model_name='couples',
            name='WeddingDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='couples',
            name='brideDOF',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='couples',
            name='groomDOF',
            field=models.DateField(null=True),
        ),
    ]
