# Generated by Django 5.0.1 on 2024-02-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_alter_couples_options_alter_couples_weddingdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couples',
            old_name='WeddingDate',
            new_name='Wedding_date',
        ),
        migrations.RenameField(
            model_name='couples',
            old_name='brideDOF',
            new_name='bride_dob',
        ),
        migrations.RenameField(
            model_name='couples',
            old_name='brideName',
            new_name='bridename',
        ),
        migrations.RenameField(
            model_name='couples',
            old_name='groomDOF',
            new_name='groom_dob',
        ),
        migrations.RenameField(
            model_name='couples',
            old_name='groomName',
            new_name='groomname',
        ),
    ]
