# Generated by Django 5.0.1 on 2024-03-16 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='date',
        ),
    ]
