# Generated by Django 5.0.1 on 2024-03-18 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0005_copulesdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='copulesdetails',
            name='enquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoice.enquiry'),
        ),
    ]
