# Generated by Django 5.0.1 on 2024-03-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0006_copulesdetails_enquiry'),
        ('venue', '0039_restrictions_user_restrictions_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='copulesdetails',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.venue'),
        ),
    ]
