# Generated by Django 5.0.1 on 2024-03-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0007_copulesdetails_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='copulesdetails',
            name='advance_paid_date',
            field=models.DateField(null=True),
        ),
    ]
