# Generated by Django 5.0.1 on 2024-03-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0009_copulesdetails_booked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='copulesdetails',
            old_name='booked',
            new_name='is_booked',
        ),
    ]
