# Generated by Django 5.0.1 on 2024-03-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0012_remove_copulesdetails_advance_amt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance_amt',
        ),
        migrations.AddField(
            model_name='invoice',
            name='enquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Invoice.enquiry'),
        ),
    ]
