# Generated by Django 5.0.1 on 2024-03-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0013_remove_invoice_balance_amt_invoice_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online Payment', 'Online Payment')], max_length=200, null=True),
        ),
    ]
