# Generated by Django 5.0.1 on 2024-03-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0014_invoice_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_amt',
        ),
    ]
