# Generated by Django 5.0.1 on 2024-03-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0015_remove_invoice_total_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
