# Generated by Django 5.0.1 on 2024-03-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0017_paymenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
    ]
