# Generated by Django 5.0.1 on 2024-03-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0019_invoicehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
