# Generated by Django 5.0.1 on 2024-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0021_invoicehistory_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicehistory',
            name='paying_amount',
            field=models.FloatField(null=True),
        ),
    ]
