# Generated by Django 5.0.1 on 2024-03-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0022_invoicehistory_paying_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='balance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_paid_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
