# Generated by Django 5.0.1 on 2024-03-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0023_invoice_balance_invoice_total_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='total_paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoicehistory',
            name='old_amount',
        ),
    ]
