# Generated by Django 5.0.1 on 2024-03-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0026_alter_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
