# Generated by Django 5.0.1 on 2024-03-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0027_alter_invoice_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='new_amt',
            field=models.FloatField(null=True),
        ),
    ]
