# Generated by Django 5.0.1 on 2024-03-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0028_invoice_new_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
