# Generated by Django 5.0.1 on 2024-03-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0030_invoice_tax_rate_invoicehistory_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='invoicehistory',
            name='tax_rate',
        ),
    ]
