# Generated by Django 5.0.1 on 2024-03-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0031_remove_invoice_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoicehistory',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
