# Generated by Django 5.0.1 on 2024-03-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0034_alter_invoice_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_rate',
        ),
    ]
