# Generated by Django 5.0.1 on 2024-03-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0035_remove_invoice_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.FloatField(null=True),
        ),
    ]
