# Generated by Django 5.0.1 on 2024-03-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0036_invoice_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicehistory',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Online Payment', 'Online Payment')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Bank Transfer', 'Bank Transfer'), ('Online Payment', 'Online Payment')], max_length=200, null=True),
        ),
    ]
