# Generated by Django 5.0.1 on 2024-03-28 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0037_invoicehistory_payment_type_and_more'),
        ('venue', '0041_venue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='venue.venue'),
        ),
    ]
