# Generated by Django 5.0.1 on 2024-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0038_enquiry_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='copulesdetails',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
