# Generated by Django 5.0.1 on 2024-02-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('vender_name', models.CharField(max_length=100, null=True)),
                ('vender_phone', models.CharField(max_length=12, null=True)),
                ('vender_email', models.EmailField(max_length=200, null=True)),
                ('vender_address', models.TextField(blank=True, null=True)),
                ('vender_city', models.CharField(max_length=200, null=True)),
                ('vender_state', models.CharField(max_length=200, null=True)),
                ('vender_zip', models.IntegerField(null=True)),
            ],
        ),
    ]
