# Generated by Django 5.0.1 on 2024-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0002_vendor_vender_image_vendor_vender_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Vender_image',
            field=models.ImageField(default='defaultvenderimg.png', null=True, upload_to=''),
        ),
    ]
