# Generated by Django 5.0.1 on 2024-02-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0004_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='service',
            field=models.CharField(choices=[('Catering', 'Catering'), ('Decor', 'Decor'), ('Photography and Videography', 'Photography and Videography'), ('Wedding Planning', 'Wedding Planning'), ('Makeup and Mehndi', 'Makeup and Mehndi'), ('Band Baja', 'Band Baja'), ('Artist Management', 'Artist Management'), ('Guest Management', 'Guest Management'), ('Transport and Logistics', 'Transport and Logistics'), ('Entertainment', 'Entertainment')], max_length=200, null=True),
        ),
    ]
