# Generated by Django 5.0.1 on 2024-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0005_vendor_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Vender_image',
            field=models.ImageField(blank=True, default='defaultvenderimg.png', null=True, upload_to=''),
        ),
    ]
