# Generated by Django 5.0.1 on 2024-02-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0006_alter_vendor_vender_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vender_about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
