# Generated by Django 5.0.1 on 2024-02-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0009_image_remove_gallery_image_gallery_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
