# Generated by Django 5.0.1 on 2024-02-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0010_delete_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
