# Generated by Django 5.0.1 on 2024-02-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0013_service_remove_vendor_service_vendor_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
