# Generated by Django 5.0.1 on 2024-02-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0015_serviceimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
