# Generated by Django 5.0.1 on 2024-02-18 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0018_serviceimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceImage',
        ),
    ]
