# Generated by Django 5.0.1 on 2024-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0020_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceimage',
            name='start_price',
            field=models.FloatField(null=True),
        ),
    ]
