# Generated by Django 5.0.1 on 2024-02-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0021_serviceimage_start_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceImage',
            new_name='ServiceDetails',
        ),
    ]
