# Generated by Django 5.0.1 on 2024-02-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0022_rename_serviceimage_servicedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
