# Generated by Django 5.0.1 on 2024-02-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0023_service_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='slug',
        ),
    ]
