# Generated by Django 5.0.1 on 2024-02-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_event_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, default=0, null=0),
        ),
    ]
