# Generated by Django 5.0.1 on 2024-02-29 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_venue_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='image',
        ),
    ]
