# Generated by Django 5.0.1 on 2024-02-29 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0005_venueimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueimage',
            name='image',
            field=models.ImageField(upload_to='venue-images/'),
        ),
        migrations.AlterField(
            model_name='venueimage',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='venue.venue'),
        ),
    ]
