# Generated by Django 5.0.1 on 2024-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_alter_venueimage_image_alter_venueimage_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(null=True, upload_to='venue-Dp/'),
        ),
    ]
