# Generated by Django 5.0.1 on 2024-03-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_venue_venue_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='booking_cost',
            field=models.FloatField(default=0),
        ),
    ]
