# Generated by Django 5.0.1 on 2024-03-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_venue_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='aminities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('pre paid', 'pre paid'), ('post paid', 'post paid')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='hall_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='amenities',
            field=models.ManyToManyField(null=True, to='venue.aminities'),
        ),
    ]
