# Generated by Django 5.0.1 on 2024-03-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_aminities_booking_booking_type_venue_hall_counts_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aminities',
            new_name='amenities',
        ),
    ]
