# Generated by Django 5.0.1 on 2024-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0013_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
