# Generated by Django 5.0.1 on 2024-03-03 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0014_remove_booking_booking_date_booking_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.venue'),
        ),
    ]
