# Generated by Django 5.0.1 on 2024-03-03 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0015_booking_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='quantity',
        ),
    ]
