# Generated by Django 5.0.1 on 2024-03-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0016_remove_booking_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
