# Generated by Django 5.0.1 on 2024-03-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0017_remove_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.BooleanField(null=True),
        ),
    ]
