# Generated by Django 5.0.1 on 2024-03-05 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0021_canclevenue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CancleVenue',
            new_name='CancelVenue',
        ),
    ]
