# Generated by Django 5.0.1 on 2024-03-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0022_rename_canclevenue_cancelvenue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CancelVenue',
        ),
    ]
