# Generated by Django 5.0.1 on 2024-03-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0025_amenities_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='booking_cost',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='city',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='hall_counts',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='state',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_image',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='zipcode',
        ),
    ]
