# Generated by Django 5.0.1 on 2024-03-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0027_venue_address_line_1_venue_address_line_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='phone_number',
        ),
    ]
