# Generated by Django 5.0.1 on 2024-03-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0030_remove_venue_amenitie_remove_venue_restriction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
