# Generated by Django 5.0.1 on 2024-03-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0032_remove_service_category_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='indoor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='max_capacity_indoor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='max_capacity_outdoor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='outdoor',
            field=models.BooleanField(default=False),
        ),
    ]
