# Generated by Django 5.0.1 on 2024-03-07 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0033_service_indoor_service_max_capacity_indoor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.venue'),
        ),
    ]
