# Generated by Django 5.0.1 on 2024-03-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0034_contactinformation_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photo',
            field=models.ImageField(null=True, upload_to='Venueprofiles'),
        ),
    ]
