# Generated by Django 5.0.1 on 2024-03-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0035_venue_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueamenities',
            name='amenitie',
        ),
        migrations.AddField(
            model_name='venueamenities',
            name='amenitie',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
