# Generated by Django 5.0.1 on 2024-03-08 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0036_remove_venueamenities_amenitie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venueamenities',
            name='amenitie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.amenities'),
        ),
    ]
