# Generated by Django 5.0.1 on 2024-03-08 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0037_amenities_user_alter_venueamenities_amenitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venue.venue'),
        ),
        migrations.DeleteModel(
            name='VenueAmenities',
        ),
    ]
